/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#004493',
        'error': '#ba1a1a',
        'text-main': '#000000',
        'primary-container': '#316ac5',
        'primary-fixed-dim': '#adc6ff',
        'secondary-fixed': '#dbe1ff',
        'header-blue-top': '#0055E5',
        'surface-container': '#f1eedd',
        'error-container': '#ffdad6',
        'border-shadow': '#ACA899',
        'secondary-container': '#2d6af9',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#adc6ff',
        'on-secondary-fixed': '#00174c',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary': '#0050d8',
        'border-dark': '#716F64',
        'dialog-face': '#ECE9D8',
        'inverse-surface': '#313126',
        'tertiary-fixed': '#77ff61',
        'tertiary-container': '#017e00',
        'outline-variant': '#c2c6d4',
        'surface-tint': '#1d5cb6',
        'tertiary': '#016200',
        'window-inner': '#FFFFFF',
        'outline': '#737783',
        'on-primary-container': '#eaeeff',
        'on-secondary-fixed-variant': '#003daa',
        'on-background': '#1c1c12',
        'on-primary-fixed': '#001a41',
        'tertiary-fixed-dim': '#30e523',
        'on-tertiary-container': '#c0ffac',
        'primary-fixed': '#d8e2ff',
        'surface-container-highest': '#e6e3d2',
        'on-error-container': '#93000a',
        'on-surface-variant': '#424752',
        'surface': '#fdfae8',
        'on-tertiary-fixed-variant': '#015300',
        'surface-container-low': '#f7f4e3',
        'secondary-fixed-dim': '#b4c5ff',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f4f1e0',
        'background': '#fdfae8',
        'surface-variant': '#e6e3d2',
        'on-secondary-container': '#fefcff',
        'surface-container-high': '#ece9d8',
        'surface-bright': '#fdfae8',
        'on-tertiary-fixed': '#002200',
        'on-surface': '#1c1c12',
        'header-blue-bottom': '#D4D0C8',
        'surface-dim': '#dddaca',
        'primary': '#0451ab',
        'on-tertiary': '#ffffff',
        'text-disabled': '#808080',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'footer-h': '47px',
        'header-h': '58px',
        'dialog-width': '497px',
        'button-h': '23px',
        'sidebar-w': '164px',
        'gutter-button': '7px',
        'margin-edge': '12px',
        'button-w': '75px',
        'dialog-height': '360px',
      },
      fontFamily: {
        'caption-small': ['Tahoma', 'sans-serif'],
        'code-eula': ['"Courier New"', 'monospace'],
        'display-welcome': ['"Trebuchet MS"', 'sans-serif'],
        'body-standard': ['Tahoma', 'sans-serif'],
        'label-button': ['Tahoma', 'sans-serif'],
        'header-title': ['Tahoma', 'sans-serif'],
      },
      fontSize: {
        'caption-small': ['10px', { lineHeight: '12px', fontWeight: '400' }],
        'code-eula': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'display-welcome': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'body-standard': ['11px', { lineHeight: '14px', fontWeight: '400' }],
        'label-button': ['11px', { lineHeight: '11px', fontWeight: '400' }],
        'header-title': ['12px', { lineHeight: '16px', fontWeight: '700' }],
      },
      width: {
        'dialog-width': '497px',
        'sidebar-w': '164px',
        'button-w': '75px',
      },
      height: {
        'dialog-height': '360px',
        'footer-h': '47px',
        'header-h': '58px',
        'button-h': '23px',
      },
    },
  },
  plugins: [],
};
